openvpn_ip: 127.0.0.1
openvpn_port: 1194
openvpn_protocol: udp

openvpn_dh: files/dh.pem

openvpn_location: /etc/openvpn

easyrsa_version: EasyRSA-3.0.1
easyrsa_url: "https://github.com/OpenVPN/easy-rsa/releases/download/3.0.1/{{ easyrsa_version }}.tgz"
clientside: "{{ openvpn_location }}/clientside"
serverside: "{{ openvpn_location }}/serverside"
easyrsa_client: "{{ clientside }}/{{ easyrsa_version }}"
easyrsa_server: "{{ serverside }}/{{ easyrsa_version }}"

openvpn_clients:
  - client1

private_subnets: []
dns_servers:
  - 8.8.8.8
  - 8.8.4.4
