---
- name: install python3
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-dev
    - python3-setuptools
    - gcc

- name: install pip3
  easy_install:
    name: pip
    state: present
    executable: easy_install3

- name: install homeassistant
  pip:
    name: homeassistant
    executable: /usr/local/bin/pip3

- name: add homeassistant.service
  template:
    src: homeassistant.service.j2
    dest: /etc/systemd/system/homeassistant.service

- name: enable homeassistant.service
  service:
    name: homeassistant
    enabled: yes
    daemon_reload: yes

- name: install config files
  git:
    repo: "{{ hass_config_repo }}"
    dest: "{{ hass_config_dir }}"
    accept_hostkey: true

- name: restart homeassistant
  service:
    name: homeassistant
    state: restarted
    daemon_reload: yes
