---
- name: install python3
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-dev
    - python3-setuptools
    - gcc

- name: install pip3
  easy_install:
    name: pip
    state: present
    executable: easy_install3

- name: install homeassistant
  pip:
    name: homeassistant
    executable: /usr/local/bin/pip3

- name: add homeassistant.service
  template:
    src: homeassistant.service.j2
    dest: /etc/systemd/system/homeassistant.service

- name: enable homeassistant.service
  service:
    name: homeassistant
    enabled: yes
    daemon_reload: yes

- name: create {{ hass_config_dir }}
  file:
    path: "{{ hass_config_dir }}"
    state: directory
    mode: 0755

- name: create {{ hass_config_dir }}/configuration.yaml
  template:
    src: config/configuration.yaml.j2
    dest: "{{ hass_config_dir }}/configuration.yaml"
    mode: 0755

- name: create {{ hass_config_dir }}/customize.yaml
  template:
    src: config/customize.yaml.j2
    dest: "{{ hass_config_dir }}/customize.yaml"
    mode: 0755

- name: restart homeassistant
  service:
    name: homeassistant
    state: restarted
    daemon_reload: yes
