---
- name: add user to staff group
  user:
    name: "{{ ansible_user }}"
    groups: staff
    append: yes
  become: yes

- name: create authorized_key entry
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ remote_access_key }}"
  register: add_identity_key
  when: remote_access_key != ""

# - block:
#   - name: create hosts.allow
#     lineinfile:
#       dest: /etc/hosts.allow
#       line: 'SSHD: {{ item }}'
#     with_items:
#       - "{{ allowed_networks }}"
#
#   - name: create hosts.deny
#     lineinfile:
#       dest: /etc/hosts.deny
#       regexp: ^SSHD
#       line: "SSHD: ALL"
#   become: yes

- block:
  - name: configure PermitEmptyPasswords
    lineinfile:
      dest: "{{ sshd_config }}"
      regexp: "^#?PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"

  - name: configure PermitRootLogin
    lineinfile:
      dest: "{{ sshd_config }}"
      regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"

  - name: configure PasswordAuthentication
    lineinfile:
      dest: "{{ sshd_config }}"
      regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    when: add_identity_key|success and not add_identity_key|skipped

  - name: configure UsePAM
    lineinfile:
      dest: "{{ sshd_config }}"
      regexp: "^#?UsePAM"
      line: "UsePAM no"

  - name: restart sshd.service
    service:
      name: "{{ sshd }}"
      state: restarted
  become: yes
